package nn

import (
	"github.com/teratron/gonn/pkg/activation"
	"github.com/teratron/gonn/pkg/loss"
	"github.com/teratron/gonn/pkg/network"
	"github.com/teratron/gonn/pkg/optimizer"
	"github.com/teratron/gonn/pkg/utils"
)

// ============================================================================
// Topology methods
// ============================================================================

// Input declares the input layer size. Calling Input twice overwrites the
// previous size with a Logger.Debug trace — useful for REPL-style
// reconfiguration before Compile.
//
// AI-Meta:
//   - Purpose: Set the number of input features in the Builder API.
//   - Usage: nn.NewBuilder[float32]().Input(4)....
//   - Concurrency: NotSafe; must be called before Compile.
//   - Related: [NN], [Compile], [WithInput].
//   - Stability: Stable.
func (n *NN[T]) Input(size uint) *NN[T] {
	if !n.guardConfiguring("Input") {
		return n
	}
	if n.cfg.InputSize != 0 {
		utils.Logger.Debug("Input size overwritten",
			"old", n.cfg.InputSize, "new", size)
	}
	n.cfg.InputSize = size
	return n
}

// Dense appends a hidden layer with the given size, activation, and bias
// setting. Invalid activation symbols surface at Compile as ErrUserConfig.
//
// AI-Meta:
//   - Purpose: Add one hidden layer in the Builder API; supports per-layer bias control.
//   - Usage: .Dense(8, activation.ReLU, true).
//   - Concurrency: NotSafe; must be called before Compile.
//   - Related: [Hidden], [WithHiddenLayer], [Compile].
//   - Stability: Stable.
func (n *NN[T]) Dense(size uint, act activation.Type, bias bool) *NN[T] {
	if !n.guardConfiguring("Dense") {
		return n
	}
	n.cfg.HiddenLayers = append(n.cfg.HiddenLayers, HiddenLayerSpec[T]{
		Size:       size,
		Activation: act,
		Bias:       bias,
	})
	return n
}

// Hidden is a documented alias for Dense, kept for callers who prefer
// input/hidden/output naming over the layer-type name.
//
// AI-Meta:
//   - Purpose: Alias for Dense; use whichever name fits the code's vocabulary.
//   - Related: [Dense], [WithHiddenLayer].
//   - Stability: Stable.
func (n *NN[T]) Hidden(size uint, act activation.Type, bias bool) *NN[T] {
	return n.Dense(size, act, bias)
}

// Output declares the output layer size, activation, and bias. Loss is set
// separately via WithLoss — structural and training concerns are on separate
// axes.
//
// AI-Meta:
//   - Purpose: Declare the output layer in the Builder API.
//   - Usage: .Output(1, activation.SIGMOID, true).WithLoss(loss.MSE).
//   - Concurrency: NotSafe; must be called before Compile.
//   - Related: [WithLoss], [WithOutput], [Compile].
//   - Stability: Stable.
func (n *NN[T]) Output(size uint, act activation.Type, bias bool) *NN[T] {
	if !n.guardConfiguring("Output") {
		return n
	}
	if n.cfg.OutputSize != 0 {
		utils.Logger.Debug("Output size overwritten",
			"old", n.cfg.OutputSize, "new", size)
	}
	n.cfg.OutputSize = size
	n.cfg.OutputActivation = act
	n.cfg.OutputBias = bias
	return n
}

// Repeat appends count identical hidden layers with the given size, activation,
// and bias to the Builder chain. For N identical layers in one call.
//
// AI-Meta:
//   - Purpose: Add N identical hidden layers in one Builder API call with explicit bias control.
//   - Usage: nn.NewBuilder[float32]().Input(784).Repeat(100, 256, activation.ReLU, true).Output(10, ...).
//   - Related: [Dense], [Pattern], [HiddenLayers], [Compile].
//   - Stability: Stable.
func (n *NN[T]) Repeat(count, size uint, act activation.Type, bias bool) *NN[T] {
	if !n.guardConfiguring("Repeat") {
		return n
	}
	for range count {
		n.cfg.HiddenLayers = append(n.cfg.HiddenLayers, HiddenLayerSpec[T]{
			Size:       size,
			Activation: act,
			Bias:       bias,
		})
	}
	return n
}

// Pattern appends block repeated repeats times to the Builder chain.
// A zero-length block or zero repeats is a no-op; Compile enforces minimum
// layer constraints. Validation errors surface at Compile (ErrUserConfig).
//
// AI-Meta:
//   - Purpose: Add a repeating multi-layer block to the Builder API topology.
//   - Usage: nn.NewBuilder[float32]().Input(784).Pattern(block, 33).Output(10, ...).
//   - Related: [Dense], [Repeat], [HiddenLayers], [Compile].
//   - Stability: Stable.
func (n *NN[T]) Pattern(block []HiddenLayerSpec[T], repeats uint) *NN[T] {
	if !n.guardConfiguring("Pattern") {
		return n
	}
	for range repeats {
		n.cfg.HiddenLayers = append(n.cfg.HiddenLayers, block...)
	}
	return n
}

// HiddenLayers replaces all previously added hidden layers with the supplied
// slice (setter semantics, not append). Use this for full programmatic control
// of the topology, e.g., layers generated by a hyperparameter search.
//
// AI-Meta:
//   - Purpose: Replace the entire hidden-layer topology with a pre-built slice in the Builder API.
//   - Usage: nn.NewBuilder[float32]().Input(784).HiddenLayers(layers).Output(10, ...).
//   - Related: [Dense], [Repeat], [Pattern], [Compile].
//   - Stability: Stable.
func (n *NN[T]) HiddenLayers(layers []HiddenLayerSpec[T]) *NN[T] {
	if !n.guardConfiguring("HiddenLayers") {
		return n
	}
	n.cfg.HiddenLayers = layers
	return n
}

// ============================================================================
// Configuration methods
// ============================================================================

// WithLearningRate sets the SGD learning rate. Non-positive values are
// accepted here but rejected by Compile with ErrUserConfig.
//
// AI-Meta:
//   - Purpose: Configure the learning rate in the Builder API.
//   - Related: [WithLearningRate], [DefaultLearningRate], [Compile].
//   - Stability: Stable.
func (n *NN[T]) WithLearningRate(rate T) *NN[T] {
	if !n.guardConfiguring("WithLearningRate") {
		return n
	}
	n.cfg.LearningRate = rate
	return n
}

// WithLoss sets the loss function symbol consumed by the training loop.
// Default at Compile is loss.MSE.
//
// AI-Meta:
//   - Purpose: Select the loss function in the Builder API.
//   - Related: [WithLoss], [loss.Type], [Compile].
//   - Stability: Stable.
func (n *NN[T]) WithLoss(lossType loss.Type) *NN[T] {
	if !n.guardConfiguring("WithLoss") {
		return n
	}
	n.cfg.LossType = lossType
	return n
}

// WithBias sets the global default bias flag for Dense/Output layers added
// after this call. Layers added before this call keep their per-call setting.
//
// AI-Meta:
//   - Purpose: Set the default bias flag for subsequently added layers in the Builder API.
//   - Related: [WithBias], [Dense], [Output].
//   - Stability: Stable.
func (n *NN[T]) WithBias(use bool) *NN[T] {
	if !n.guardConfiguring("WithBias") {
		return n
	}
	n.cfg.DefaultBias = use
	return n
}

// WithWeightInit selects the weight-initialisation strategy. Unknown methods
// are accepted here but rejected by Compile with ErrUserConfig.
//
// AI-Meta:
//   - Purpose: Select the weight-init strategy in the Builder API.
//   - Related: [WithWeightInit], [WeightInitMethod], [Compile].
//   - Stability: Stable.
func (n *NN[T]) WithWeightInit(method WeightInitMethod) *NN[T] {
	if !n.guardConfiguring("WithWeightInit") {
		return n
	}
	n.cfg.WeightInit = method
	return n
}

// WithLossLimit sets the early-stopping threshold; Fit returns once the mean
// epoch loss drops below this value. Default at Compile is DefaultLossLimit.
//
// AI-Meta:
//   - Purpose: Set the early-stopping loss threshold in the Builder API.
//   - Related: [WithLossLimit], [DefaultLossLimit], [Fit].
//   - Stability: Stable.
func (n *NN[T]) WithLossLimit(threshold T) *NN[T] {
	if !n.guardConfiguring("WithLossLimit") {
		return n
	}
	n.cfg.LossLimit = threshold
	return n
}

// WithMaxIterations bounds the training loop to at most count epochs.
// Default at Compile is DefaultMaxIterations.
//
// AI-Meta:
//   - Purpose: Cap the number of training epochs in the Builder API.
//   - Related: [WithMaxIterations], [DefaultMaxIterations], [Fit].
//   - Stability: Stable.
func (n *NN[T]) WithMaxIterations(count uint) *NN[T] {
	if !n.guardConfiguring("WithMaxIterations") {
		return n
	}
	n.cfg.MaxIterations = count
	return n
}

// ============================================================================
// Callback methods
// ============================================================================

// WithEpochCallback registers a callback invoked at the end of every epoch.
// The callback is synchronous — a slow callback blocks the training loop.
// Pass nil to disable a previously-set callback.
//
// AI-Meta:
//   - Purpose: Register an epoch-level progress hook for logging or early-stopping logic.
//   - Concurrency: SingleGoroutine.
//   - Related: [WithEpochCallback], [WithBatchCallback], [Fit].
//   - Stability: Stable.
func (n *NN[T]) WithEpochCallback(fn func(epoch uint, lossValue T)) *NN[T] {
	if !n.guardConfiguring("WithEpochCallback") {
		return n
	}
	n.cfg.EpochCallback = fn
	return n
}

// WithBatchCallback registers a callback invoked at the end of every batch.
// Synchronous; same caveats as WithEpochCallback.
//
// AI-Meta:
//   - Purpose: Register a batch-level progress hook for fine-grained loss monitoring.
//   - Concurrency: SingleGoroutine.
//   - Related: [WithBatchCallback], [WithEpochCallback], [Fit].
//   - Stability: Stable.
func (n *NN[T]) WithBatchCallback(fn func(batch uint, lossValue T)) *NN[T] {
	if !n.guardConfiguring("WithBatchCallback") {
		return n
	}
	n.cfg.BatchCallback = fn
	return n
}

// WithScheduler attaches a learning-rate scheduler to the network. The
// scheduler's Step is called by the training loop at the interval defined
// by its Granularity. nil disables scheduling (default).
//
// AI-Meta:
//   - Purpose: Attach an LR scheduler in the Builder API.
//   - Usage: nn.NewBuilder[float32]()....WithScheduler(optimizer.BindScheduler(opt, sched)).Compile().
//   - Related: [WithScheduler], [optimizer.Scheduler], [optimizer.BindScheduler].
//   - Stability: Stable.
func (n *NN[T]) WithScheduler(sched optimizer.Scheduler[T]) *NN[T] {
	if !n.guardConfiguring("WithScheduler") {
		return n
	}
	n.cfg.Scheduler = sched
	return n
}

// WithTopologyMode opts the network into dynamic topology mutation after
// compile. Pass network.Dynamic to enable AddNeuron / AddHiddenLayer etc.
//
// AI-Meta:
//   - Purpose: Opt in to dynamic topology at compile time via the Builder API.
//   - Related: [network.TopologyMode], [WithTopologyMode].
//   - Stability: Stable.
func (n *NN[T]) WithTopologyMode(mode network.TopologyMode) *NN[T] {
	if !n.guardConfiguring("WithTopologyMode") {
		return n
	}
	n.cfg.TopologyMode = mode
	return n
}

// ============================================================================
// Finalisation
// ============================================================================

// Compile validates the staged configuration, applies defaults, builds the
// underlying network graph, and transitions the NN to Operational state.
// Returns the same *NN[T] for chain-style assignments.
//
// Idempotent on Operational networks: a second call returns (n, ErrUserConfig).
// Builder methods called after Compile emit Logger.Warn and become no-ops.
//
// AI-Meta:
//   - Purpose: Finalise topology, validate config, and wire all axons; required before Train/Query.
//   - Lifecycle: Configuring → Operational on success.
//   - Concurrency: SingleGoroutine; must complete before sharing NN across goroutines.
//   - Errors: ErrUserConfig (missing layers, zero sizes, bad rate, unknown activation/loss/init).
//   - Related: [NewBuilder], [New], [MustCompile], [network.Network.Build].
//   - Constraints: Idempotent; topology cannot be mutated after success.
//   - Stability: Stable.
func (n *NN[T]) Compile() (*NN[T], error) {
	switch n.stateField {
	case stateOperational:
		return n, utils.Newf(utils.ErrUserConfig, "Compile: network already compiled (idempotent: returning existing instance)")
	case stateUninitialized:
		return nil, utils.Newf(utils.ErrUserConfig, "Compile: network is uninitialised — use NewBuilder() or New(opts...)")
	}
	if err := compile(n, &n.cfg); err != nil {
		return nil, err
	}
	n.stateField = stateOperational
	return n, nil
}

// MustCompile is the panicking variant of Compile, intended for examples
// and tests where a compile failure is a programming bug.
//
// AI-Meta:
//   - Purpose: Panicking wrapper around Compile; eliminates error handling in non-production contexts.
//   - Related: [Compile], [MustNew].
//   - Stability: Stable.
func (n *NN[T]) MustCompile() *NN[T] {
	out, err := n.Compile()
	if err != nil {
		panic("nn.MustCompile: " + err.Error())
	}
	return out
}
