name: perceptron
bias: false
hidden:
  - 3
  - 2
activation: 3
loss: 0
limit: 1e-7
rate: 0.3
weights:
  - - - 0.8,
      - 0.2
    - - 0.4,
      - 0.9
    - - 0.3,
      - 0.5
  - - - 0.3,
      - 0.5,
      - 0.9
